[build]
    publish = "dist/"
    command = "npm run deploy"

[[plugins]]
package = "netlify-plugin-cache"
    [plugins.inputs]
    paths = ['.webpack']

[build.processing]
    skip_processing = false
