:Author: Ben Martinez-Bateman
:Email: ben@alwaysblank.org
:toc: macro
:toclevels: 3
:toc-title:
:sectanchors:
:sectlinks:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: ðŸ’¡
:note-caption: â„¹
:important-caption: â—
:caution-caption: ðŸ”¥
:warning-caption: âš 
endif::[]

= Elfin ðŸ§

An opinionated template for building a site based on link:https:11ty.dev[11ty] and link:https://tailwindcss.com[Tailwind].

toc::[]

== What Do You Get

- Simple server w/ BrowserSync that watches changes to styles, scripts, and content
- Delivers modern JS to modern browsers, and shitty JS to shitty browsers
- Tailwind!
- Minimizes and optimizes CSS and JS
- Lossless compression of images (jpg, png, svg)

== How Do I Use It

- `npm run build` - Builds the entire site into the `dist` directory
- `npm run all:production` - Run a production build (use this when deploying).
- `npm run serve` - Builds, watches, and serves the site at https://localhost:8080

[WARNING]
====
Because there are essentially two "builds" that happen here (11ty and Webpack) there is a bit of _file shuffling_ that goes on.
**If a directory or file is in `.gitignore` then it is probably part of that shuffling and you should leave it alone.** i.e. `site/assets/`, `content/_data/assets.json`, etc.
====

[source,shell script]
----
elfin/                    # -> Your project directory
â”œâ”€â”€ 11ty                  # -> Extensions to 11ty
â”‚  â”œâ”€â”€ index.js           # -> Collects filters, shortcodes, etc
â”‚  â”œâ”€â”€ filters/           # -> Add custom filters here
â”‚  â””â”€â”€ shortcodes/        # -> Add custom shortcodes here
â”œâ”€â”€ assets                # -> Assets that will be process by webpack
â”‚  â”œâ”€â”€ entry.js           # -> Defines JS, CSS, for build process
â”‚  â”œâ”€â”€ legacy.js          # -> Defines "legacy" build -- add polyfills here
â”‚  â”œâ”€â”€ images/            # -> Images to be ingested by build process
â”‚  â”œâ”€â”€ scripts/           # -> All your JavaScript
â”‚  â””â”€â”€ styles/            # -> All your CSS
â”œâ”€â”€ content               # -> Files used by 11ty to build the site
â”‚  â”œâ”€â”€ _data/             # -> 11ty global data files
â”‚  â”œâ”€â”€ _includes/         # -> 11ty include, partials, etc
â”‚  â”œâ”€â”€ _layouts/          # -> 11ty layouts
â”‚  â”œâ”€â”€ assets/            # -> Used by build process -- don't touch!
â”‚  â””â”€â”€ index.njk          # -> Example template
â”œâ”€â”€ dist/                 # -> Where the site is built to -- don't touch!
â”œâ”€â”€ docs/                 # -> Additional documentation
â”œâ”€â”€ README.adoc           # -> This document!
â”œâ”€â”€ package.json          # -> JavaScript Dependencies
â”œâ”€â”€ eleventy.config.js    # -> 11ty configuration
â”œâ”€â”€ postcss.config.js     # -> PostCSS configuration
â”œâ”€â”€ tailwind.config.js    # -> Tailwind configuration
â””â”€â”€ webpack.config.js     # -> Webpack configuration
----

== Documentation

include::docs/shortcodes.adoc[leveloffset=+2]

include::docs/filters.adoc[leveloffset=+2]

include::docs/extending.adoc[leveloffset=+2]

== Resources

- A lot of what this package does is based on link:https://philipwalton.com/articles/deploying-es2015-code-in-production-today/[this article] and link:https://github.com/philipwalton/webpack-esnext-boilerplate[this repo] that implements the article's advice.
- There is a potential issue w/ the above technique where scripts are loaded twice.
    link:https://jasonformat.com/modern-script-loading/[This article] offers some ways to defeat that, depending on the context.
    Currently VIty doesn't implement any of these solutions, but it could.

== Why "Elfin"

"Elf" is "11" in German.
"11ty" is a cheeky way to write something like "eleven-like" or "in the manner of 11," and "-in" can be used in a similar way (i.e. the world "Elfin" does actually mean "elf-like").
Also, if you say "Elfin" out loud it kind of sounds like "eleven"...if you do the auditory equivalent of squinting.
