= Elfin 🧝

An opinionated template for building a site based on link:https:11ty.dev[11ty] and link:https://tailwindcss.com[Tailwind].

== What Do You Get

- Simple server w/ BrowserSync that watches changes to styles, scripts, and content
- Delivers modern JS to modern browsers, and shitty JS to shitty browsers
- Tailwind!
- Minimizes and optimizes CSS and JS
- Lossless compression of images (jpg, png, svg)

== How Do I Use It

- `npm run build` - Builds the entire site into the `dist` directory
- `npm run serve` - Builds, watches, and serves the site at https://localhost:8080

== Documentation

- link:docs/shortcodes.adoc[Shortcodes]

== Resources

- A lot of what this package does is based on link:https://philipwalton.com/articles/deploying-es2015-code-in-production-today/[this article] and link:https://github.com/philipwalton/webpack-esnext-boilerplate[this repo] that implements the article's advice.
- There is a potential issue w/ the above technique where scripts are loaded twice.
    link:https://jasonformat.com/modern-script-loading/[This article] offers some ways to defeat that, depending on the context.
    Currently VIty doesn't implement any of these solutions, but it could.

== Why "Elfin"

"Elf" is "11" in German.
"11ty" is a cheeky way to write something like "eleven-like" or "in the manner of 11," and "-in" can be used in a similar way (i.e. the world "Elfin" does actually mean "elf-like").
Also, if you say "Elfin" out loud it kind of sounds like "eleven"...if you do the auditory equivalent of squinting.
