#!/usr/bin/env node

const {
    readFileSync
} = require('fs')
const {
    join
} = require('path')
const {
    logError
} = require('./helpers')

try {
    const package = require(join(process.cwd(), 'package.json'))

    require('yargs/yargs')(process.argv.slice(2))
        .scriptName('elf')
        .commandDir('cmds')
        .demandCommand()
        .help()
        .fail((msg, err, yargs) => {
            if (err) throw err
            logError(msg)
            process.exit(1)
        })
        .argv
} catch (err) {
    if ('MODULE_NOT_FOUND' === err.code) {
        logError("Please run me from the project root!")
        return;
    }

    console.error(err)
}